# @get
GET https://cmc-json-code-phone.herokuapp.com/api/user/30
# @post ađ
###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "username":"nguyenthuan281294",
    "code":13
}

